steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/backend'
      - '-f'
      - 'backend/Dockerfile'
      - 'backend/'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/backend'

substitutions:
  _REGION: europe-west1
  _REPOSITORY: cheungprey

timeout: 1200s
