-- =============================================================================
-- sync_prod_to_uat.sql
-- Sync missing indexes and RLS policies from Production to UAT
-- =============================================================================

-- 1. Indexes from Production
CREATE INDEX IF NOT EXISTS idx_cron_logs_created_at ON public.cron_logs USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cron_logs_job_key ON public.cron_logs USING btree (job_key);
CREATE INDEX IF NOT EXISTS idx_finance_attachments_file ON public.finance_attachments USING btree (file_id);
CREATE INDEX IF NOT EXISTS idx_finance_budget_period ON public.finance_budgets USING btree (period_start, period_end);
CREATE INDEX IF NOT EXISTS idx_finance_budget_zone ON public.finance_budgets USING btree (zone_code);
CREATE INDEX IF NOT EXISTS idx_fms_audit_log_performed ON public.fms_audit_log USING btree (performed_at DESC);
CREATE INDEX IF NOT EXISTS idx_fms_audit_log_record ON public.fms_audit_log USING btree (table_name, record_id);
CREATE UNIQUE INDEX IF NOT EXISTS fms_budgets_zone_code_fiscal_year_account_code_key ON public.fms_budgets USING btree (zone_code, fiscal_year, account_code);
CREATE INDEX IF NOT EXISTS idx_fms_budgets_account ON public.fms_budgets USING btree (account_code);
CREATE INDEX IF NOT EXISTS idx_fms_budgets_zone ON public.fms_budgets USING btree (zone_code, fiscal_year);
CREATE INDEX IF NOT EXISTS idx_fms_transactions_account ON public.fms_transactions USING btree (account_code);
CREATE INDEX IF NOT EXISTS idx_fms_transactions_reversal ON public.fms_transactions USING btree (reversal_of);
CREATE INDEX IF NOT EXISTS idx_fms_transactions_status ON public.fms_transactions USING btree (status);
CREATE INDEX IF NOT EXISTS idx_fms_transactions_zone ON public.fms_transactions USING btree (zone_code);
CREATE INDEX IF NOT EXISTS idx_zone_parent ON public.geographic_zones USING btree (parent_code);
CREATE INDEX IF NOT EXISTS idx_activity_date ON public.member_activity USING btree (activity_date);
CREATE INDEX IF NOT EXISTS idx_activity_member ON public.member_activity USING btree (member_id);
CREATE INDEX IF NOT EXISTS idx_activity_type ON public.member_activity USING btree (activity_type);
CREATE INDEX IF NOT EXISTS idx_cards_member ON public.member_cards USING btree (member_id);
CREATE INDEX IF NOT EXISTS idx_cards_status ON public.member_cards USING btree (card_status);
CREATE INDEX IF NOT EXISTS idx_demographics_member ON public.member_demographics USING btree (member_id);
CREATE INDEX IF NOT EXISTS idx_dues_date ON public.member_dues USING btree (payment_date);
CREATE INDEX IF NOT EXISTS idx_dues_member ON public.member_dues USING btree (member_id);
CREATE INDEX IF NOT EXISTS idx_dues_status ON public.member_dues USING btree (payment_status);
CREATE INDEX IF NOT EXISTS idx_positions_current ON public.member_positions USING btree (is_current);
CREATE INDEX IF NOT EXISTS idx_positions_member ON public.member_positions USING btree (member_id);
CREATE INDEX IF NOT EXISTS idx_member_registration_documents_registration ON public.member_registration_documents USING btree (registration_id);
CREATE UNIQUE INDEX IF NOT EXISTS member_registration_documents_registration_id_document_type_key ON public.member_registration_documents USING btree (registration_id, document_type);
CREATE INDEX IF NOT EXISTS idx_member_registration_events_registration ON public.member_registration_events USING btree (registration_id, created_at);
CREATE INDEX IF NOT EXISTS idx_member_registrations_national_id ON public.member_registrations USING btree (national_id) WHERE (national_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_member_registrations_status ON public.member_registrations USING btree (status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_status_history_date ON public.member_status_history USING btree (changed_at);
CREATE INDEX IF NOT EXISTS idx_status_history_member ON public.member_status_history USING btree (member_id);
CREATE INDEX IF NOT EXISTS idx_member_location ON public.members USING btree (registered_village_code);
CREATE INDEX IF NOT EXISTS idx_member_names ON public.members USING btree (last_name_kh, first_name_kh);
CREATE INDEX IF NOT EXISTS idx_member_structure ON public.members USING btree (structure_id);
CREATE INDEX IF NOT EXISTS idx_members_card_no ON public.members USING btree (membership_card_no);
CREATE INDEX IF NOT EXISTS idx_members_national_id ON public.members USING btree (national_id) WHERE (national_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_members_status ON public.members USING btree (status);
CREATE INDEX IF NOT EXISTS idx_members_village ON public.members USING btree (registered_village_code);
CREATE INDEX IF NOT EXISTS idx_menu_items_module ON public.menu_items USING btree (module_key);
CREATE INDEX IF NOT EXISTS idx_menu_items_parent ON public.menu_items USING btree (parent_id);
CREATE INDEX IF NOT EXISTS idx_menu_items_sort ON public.menu_items USING btree (sort_order);
CREATE INDEX IF NOT EXISTS idx_menu_items_sub_module ON public.menu_items USING btree (sub_module);
CREATE INDEX IF NOT EXISTS idx_party_files_deleted ON public.party_files USING btree (deleted_at);
CREATE INDEX IF NOT EXISTS idx_party_files_folder ON public.party_files USING btree (folder_id) WHERE (deleted_at IS NULL);
CREATE INDEX IF NOT EXISTS idx_party_files_member ON public.party_files USING btree (member_id);
CREATE INDEX IF NOT EXISTS idx_party_files_uploader ON public.party_files USING btree (uploaded_by);
CREATE INDEX IF NOT EXISTS idx_finance_created_by ON public.party_finances USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_finance_date ON public.party_finances USING btree (transaction_date);
CREATE INDEX IF NOT EXISTS idx_finance_member ON public.party_finances USING btree (member_id);
CREATE INDEX IF NOT EXISTS idx_finance_status ON public.party_finances USING btree (status);
CREATE INDEX IF NOT EXISTS idx_finance_zone ON public.party_finances USING btree (zone_code);
CREATE INDEX IF NOT EXISTS idx_party_folders_deleted ON public.party_folders USING btree (deleted_at);
CREATE INDEX IF NOT EXISTS idx_party_folders_parent ON public.party_folders USING btree (parent_id) WHERE (deleted_at IS NULL);
CREATE UNIQUE INDEX IF NOT EXISTS uq_party_folders_name_parent ON public.party_folders USING btree (COALESCE(parent_id, '00000000-0000-0000-0000-000000000000'::uuid), name) WHERE (deleted_at IS NULL);
CREATE INDEX IF NOT EXISTS idx_pdf_jobs_created_at ON public.pdf_jobs USING btree (created_at);
CREATE INDEX IF NOT EXISTS idx_pdf_jobs_status ON public.pdf_jobs USING btree (status);
CREATE INDEX IF NOT EXISTS idx_performance_data_indicator ON public.performance_data USING btree (indicator_id);
CREATE INDEX IF NOT EXISTS idx_performance_data_zone ON public.performance_data USING btree (zone_id, period_id);
CREATE UNIQUE INDEX IF NOT EXISTS performance_data_zone_id_indicator_id_period_id_key ON public.performance_data USING btree (zone_id, indicator_id, period_id);
CREATE UNIQUE INDEX IF NOT EXISTS performance_indicators_sub_domain_id_code_key ON public.performance_indicators USING btree (sub_domain_id, code);
CREATE UNIQUE INDEX IF NOT EXISTS performance_sub_domains_domain_id_code_key ON public.performance_sub_domains USING btree (domain_id, code);
CREATE INDEX IF NOT EXISTS idx_performance_submissions_period ON public.performance_submissions USING btree (period_id);
CREATE INDEX IF NOT EXISTS idx_performance_submissions_zone ON public.performance_submissions USING btree (zone_id);
CREATE UNIQUE INDEX IF NOT EXISTS performance_submissions_zone_id_period_id_key ON public.performance_submissions USING btree (zone_id, period_id);
CREATE INDEX IF NOT EXISTS idx_profiles_email ON public.profiles USING btree (email);
CREATE INDEX IF NOT EXISTS idx_profiles_zone_code ON public.profiles USING btree (zone_code);
CREATE INDEX IF NOT EXISTS idx_qr_login_tokens_token ON public.qr_login_tokens USING btree (token);
CREATE INDEX IF NOT EXISTS idx_qr_login_tokens_user_id ON public.qr_login_tokens USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_report_documents_category ON public.report_documents USING btree (category);
CREATE INDEX IF NOT EXISTS idx_report_documents_created_by ON public.report_documents USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_report_documents_deleted_at ON public.report_documents USING btree (deleted_at);
CREATE INDEX IF NOT EXISTS idx_report_documents_period ON public.report_documents USING btree (report_year, report_month);
CREATE INDEX IF NOT EXISTS idx_report_documents_title ON public.report_documents USING btree (title);
CREATE INDEX IF NOT EXISTS idx_report_documents_updated_at ON public.report_documents USING btree (updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_report_documents_zone_code ON public.report_documents USING btree (zone_code);
CREATE INDEX IF NOT EXISTS idx_report_reviews_created_at ON public.report_reviews USING btree (created_at);
CREATE INDEX IF NOT EXISTS idx_report_reviews_report_id ON public.report_reviews USING btree (report_id);
CREATE INDEX IF NOT EXISTS idx_report_template_keys_template_id ON public.report_template_keys USING btree (template_id);
CREATE INDEX IF NOT EXISTS idx_report_template_keys_tmpl ON public.report_template_keys USING btree (template_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_report_template_keys_tmpl_key ON public.report_template_keys USING btree (template_id, key_name);
CREATE INDEX IF NOT EXISTS idx_report_templates_category ON public.report_templates USING btree (category);
CREATE INDEX IF NOT EXISTS idx_report_templates_created_at ON public.report_templates USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_report_templates_created_by ON public.report_templates USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_report_templates_format ON public.report_templates USING btree (format);
CREATE INDEX IF NOT EXISTS idx_report_templates_updated_at ON public.report_templates USING btree (updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_sponsorship_items_name ON public.sponsorship_items USING btree (item_name);
CREATE INDEX IF NOT EXISTS idx_sponsorship_items_record_id ON public.sponsorship_items USING btree (record_id);
CREATE INDEX IF NOT EXISTS idx_sponsorship_records_contributor ON public.sponsorship_records USING btree (contributor_name);
CREATE INDEX IF NOT EXISTS idx_sponsorship_records_period ON public.sponsorship_records USING btree (record_period);
CREATE INDEX IF NOT EXISTS idx_sponsorship_records_year ON public.sponsorship_records USING btree (fiscal_year);
CREATE INDEX IF NOT EXISTS idx_system_settings_category ON public.system_settings USING btree (category);
CREATE INDEX IF NOT EXISTS idx_system_settings_key ON public.system_settings USING btree (key);
CREATE INDEX IF NOT EXISTS idx_user_roles_user ON public.user_roles USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_voter_sentiment ON public.voter_insights USING btree (commune_code, voter_sentiment);
CREATE INDEX IF NOT EXISTS idx_wf_approvals_approver ON public.workflow_approvals USING btree (approver_id, status);
CREATE INDEX IF NOT EXISTS idx_wf_approvals_item ON public.workflow_approvals USING btree (module_key, item_id);
CREATE INDEX IF NOT EXISTS idx_wf_approvals_queue ON public.workflow_approvals USING btree (module_key, step_order, status);
CREATE UNIQUE INDEX IF NOT EXISTS workflow_approvals_module_key_item_id_step_order_key ON public.workflow_approvals USING btree (module_key, item_id, step_order);
CREATE UNIQUE INDEX IF NOT EXISTS workflow_steps_module_key_step_order_key ON public.workflow_steps USING btree (module_key, step_order);
CREATE INDEX IF NOT EXISTS idx_zone_chief_assignments_user ON public.zone_chief_assignments USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_zone_chief_assignments_zone ON public.zone_chief_assignments USING btree (zone_code);

-- 2. RLS Policies from Production
ALTER TABLE public."chart_of_accounts" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admin can manage chart_of_accounts" ON public."chart_of_accounts";
CREATE POLICY "Admin can manage chart_of_accounts" ON public."chart_of_accounts" FOR ALL TO authenticated USING ((get_user_role() = ANY (ARRAY['super_admin'::text, 'admin'::text]))) WITH CHECK ((get_user_role() = ANY (ARRAY['super_admin'::text, 'admin'::text])));
ALTER TABLE public."chart_of_accounts" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Authenticated can read chart_of_accounts" ON public."chart_of_accounts";
CREATE POLICY "Authenticated can read chart_of_accounts" ON public."chart_of_accounts" FOR SELECT TO authenticated USING (true);
ALTER TABLE public."fms_audit_log" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admin can read fms_audit_log" ON public."fms_audit_log";
CREATE POLICY "Admin can read fms_audit_log" ON public."fms_audit_log" FOR SELECT TO authenticated USING ((get_user_role() = ANY (ARRAY['super_admin'::text, 'admin'::text])));
ALTER TABLE public."fms_budgets" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admin can manage fms_budgets" ON public."fms_budgets";
CREATE POLICY "Admin can manage fms_budgets" ON public."fms_budgets" FOR ALL TO authenticated USING ((get_user_role() = ANY (ARRAY['super_admin'::text, 'admin'::text]))) WITH CHECK ((get_user_role() = ANY (ARRAY['super_admin'::text, 'admin'::text])));
ALTER TABLE public."fms_budgets" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Staff can read fms_budgets" ON public."fms_budgets";
CREATE POLICY "Staff can read fms_budgets" ON public."fms_budgets" FOR SELECT TO authenticated USING (true);
ALTER TABLE public."fms_transactions" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admin can manage fms_transactions" ON public."fms_transactions";
CREATE POLICY "Admin can manage fms_transactions" ON public."fms_transactions" FOR ALL TO authenticated USING ((get_user_role() = ANY (ARRAY['super_admin'::text, 'admin'::text]))) WITH CHECK ((get_user_role() = ANY (ARRAY['super_admin'::text, 'admin'::text])));
ALTER TABLE public."fms_transactions" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can read own zone fms_transactions" ON public."fms_transactions";
CREATE POLICY "Users can read own zone fms_transactions" ON public."fms_transactions" FOR SELECT TO authenticated USING (((get_user_role() = ANY (ARRAY['super_admin'::text, 'admin'::text])) OR ((zone_code)::text = (( SELECT profiles.zone_code
   FROM profiles
  WHERE (profiles.id = auth.uid())))::text)));
ALTER TABLE public."party_files" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Authenticated can manage files" ON public."party_files";
CREATE POLICY "Authenticated can manage files" ON public."party_files" FOR ALL TO public USING ((auth.uid() IS NOT NULL)) WITH CHECK ((auth.uid() IS NOT NULL));
ALTER TABLE public."party_folders" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Authenticated can manage folders" ON public."party_folders";
CREATE POLICY "Authenticated can manage folders" ON public."party_folders" FOR ALL TO public USING ((auth.uid() IS NOT NULL)) WITH CHECK ((auth.uid() IS NOT NULL));
ALTER TABLE public."profiles" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Super admin and admin can update profiles" ON public."profiles";
CREATE POLICY "Super admin and admin can update profiles" ON public."profiles" FOR UPDATE TO public USING ((get_user_role() = ANY (ARRAY['super_admin'::text, 'admin'::text])));
ALTER TABLE public."profiles" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Super admin and admin can view all profiles" ON public."profiles";
CREATE POLICY "Super admin and admin can view all profiles" ON public."profiles" FOR SELECT TO public USING ((get_user_role() = ANY (ARRAY['super_admin'::text, 'admin'::text])));
ALTER TABLE public."records" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admin can manage all records" ON public."records";
CREATE POLICY "Admin can manage all records" ON public."records" FOR ALL TO public USING ((get_user_role() = 'admin'::text));
ALTER TABLE public."records" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Commune chief can manage commune records" ON public."records";
CREATE POLICY "Commune chief can manage commune records" ON public."records" FOR ALL TO public USING (((get_user_role() = 'commune_chief'::text) AND (commune_id = get_user_commune())));
ALTER TABLE public."records" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Commune clerk can manage commune records" ON public."records";
CREATE POLICY "Commune clerk can manage commune records" ON public."records" FOR ALL TO public USING (((get_user_role() = 'commune_clerk'::text) AND (commune_id = get_user_commune())));
ALTER TABLE public."records" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Commune clerk can view commune records" ON public."records";
CREATE POLICY "Commune clerk can view commune records" ON public."records" FOR SELECT TO public USING (((get_user_role() = 'commune_clerk'::text) AND (commune_id = get_user_commune())));
ALTER TABLE public."records" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "District chief can view records in district" ON public."records";
CREATE POLICY "District chief can view records in district" ON public."records" FOR SELECT TO public USING (((get_user_role() = 'district_chief'::text) AND (commune_id IN ( SELECT communes.id
   FROM communes
  WHERE (communes.district_id IN ( SELECT communes_1.district_id
           FROM communes communes_1
          WHERE (communes_1.id = get_user_commune())))))));
ALTER TABLE public."records" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Recorder can create records" ON public."records";
CREATE POLICY "Recorder can create records" ON public."records" FOR INSERT TO public WITH CHECK ((get_user_role() = 'recorder'::text));
ALTER TABLE public."records" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Super admin can do everything" ON public."records";
CREATE POLICY "Super admin can do everything" ON public."records" FOR ALL TO public USING ((get_user_role() = 'super_admin'::text));
ALTER TABLE public."records" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Village chief can manage village records" ON public."records";
CREATE POLICY "Village chief can manage village records" ON public."records" FOR ALL TO public USING (((get_user_role() = 'village_chief'::text) AND (village_id = get_user_village())));
ALTER TABLE public."report_documents" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Staff can manage report documents" ON public."report_documents";
CREATE POLICY "Staff can manage report documents" ON public."report_documents" FOR ALL TO public USING ((get_user_role() = ANY (ARRAY['super_admin'::text, 'admin'::text, 'district_chief'::text, 'commune_chief'::text, 'commune_clerk'::text, 'village_chief'::text, 'recorder'::text])));
ALTER TABLE public."report_template_keys" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "template_keys_delete" ON public."report_template_keys";
CREATE POLICY "template_keys_delete" ON public."report_template_keys" FOR DELETE TO authenticated USING ((auth.uid() IS NOT NULL));
ALTER TABLE public."report_template_keys" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "template_keys_insert" ON public."report_template_keys";
CREATE POLICY "template_keys_insert" ON public."report_template_keys" FOR INSERT TO authenticated WITH CHECK ((auth.uid() IS NOT NULL));
ALTER TABLE public."report_template_keys" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "template_keys_select" ON public."report_template_keys";
CREATE POLICY "template_keys_select" ON public."report_template_keys" FOR SELECT TO authenticated USING (true);
ALTER TABLE public."report_template_keys" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "template_keys_update" ON public."report_template_keys";
CREATE POLICY "template_keys_update" ON public."report_template_keys" FOR UPDATE TO authenticated USING ((auth.uid() IS NOT NULL));
ALTER TABLE public."report_templates" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admin can manage report templates" ON public."report_templates";
CREATE POLICY "Admin can manage report templates" ON public."report_templates" FOR ALL TO public USING ((get_user_role() = ANY (ARRAY['super_admin'::text, 'admin'::text])));
ALTER TABLE public."report_templates" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Staff can read report templates" ON public."report_templates";
CREATE POLICY "Staff can read report templates" ON public."report_templates" FOR SELECT TO public USING ((get_user_role() = ANY (ARRAY['super_admin'::text, 'admin'::text, 'district_chief'::text, 'commune_chief'::text, 'commune_clerk'::text, 'village_chief'::text, 'recorder'::text])));
ALTER TABLE public."role_permissions" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admin can update role_permissions" ON public."role_permissions";
CREATE POLICY "Admin can update role_permissions" ON public."role_permissions" FOR ALL TO public USING ((get_user_role() = ANY (ARRAY['super_admin'::text, 'admin'::text])));
ALTER TABLE public."role_permissions" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Anyone authenticated can read role_permissions" ON public."role_permissions";
CREATE POLICY "Anyone authenticated can read role_permissions" ON public."role_permissions" FOR SELECT TO public USING ((auth.uid() IS NOT NULL));
ALTER TABLE public."roles" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admin can manage roles" ON public."roles";
CREATE POLICY "Admin can manage roles" ON public."roles" FOR ALL TO authenticated USING ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = ANY (ARRAY['super_admin'::text, 'admin'::text])))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = ANY (ARRAY['super_admin'::text, 'admin'::text]))))));
ALTER TABLE public."roles" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Anyone authenticated can read roles" ON public."roles";
CREATE POLICY "Anyone authenticated can read roles" ON public."roles" FOR SELECT TO authenticated USING (true);
ALTER TABLE public."sponsorship_items" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated delete sponsorship_items" ON public."sponsorship_items";
CREATE POLICY "Allow authenticated delete sponsorship_items" ON public."sponsorship_items" FOR DELETE TO authenticated USING (true);
ALTER TABLE public."sponsorship_items" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated insert sponsorship_items" ON public."sponsorship_items";
CREATE POLICY "Allow authenticated insert sponsorship_items" ON public."sponsorship_items" FOR INSERT TO authenticated WITH CHECK (true);
ALTER TABLE public."sponsorship_items" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated read sponsorship_items" ON public."sponsorship_items";
CREATE POLICY "Allow authenticated read sponsorship_items" ON public."sponsorship_items" FOR SELECT TO authenticated USING (true);
ALTER TABLE public."sponsorship_items" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated update sponsorship_items" ON public."sponsorship_items";
CREATE POLICY "Allow authenticated update sponsorship_items" ON public."sponsorship_items" FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
ALTER TABLE public."sponsorship_periods" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated delete sponsorship_periods" ON public."sponsorship_periods";
CREATE POLICY "Allow authenticated delete sponsorship_periods" ON public."sponsorship_periods" FOR DELETE TO authenticated USING (true);
ALTER TABLE public."sponsorship_periods" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated insert sponsorship_periods" ON public."sponsorship_periods";
CREATE POLICY "Allow authenticated insert sponsorship_periods" ON public."sponsorship_periods" FOR INSERT TO authenticated WITH CHECK (true);
ALTER TABLE public."sponsorship_periods" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated read sponsorship_periods" ON public."sponsorship_periods";
CREATE POLICY "Allow authenticated read sponsorship_periods" ON public."sponsorship_periods" FOR SELECT TO authenticated USING (true);
ALTER TABLE public."sponsorship_periods" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated update sponsorship_periods" ON public."sponsorship_periods";
CREATE POLICY "Allow authenticated update sponsorship_periods" ON public."sponsorship_periods" FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
ALTER TABLE public."sponsorship_records" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated delete sponsorship_records" ON public."sponsorship_records";
CREATE POLICY "Allow authenticated delete sponsorship_records" ON public."sponsorship_records" FOR DELETE TO authenticated USING (true);
ALTER TABLE public."sponsorship_records" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated insert sponsorship_records" ON public."sponsorship_records";
CREATE POLICY "Allow authenticated insert sponsorship_records" ON public."sponsorship_records" FOR INSERT TO authenticated WITH CHECK (true);
ALTER TABLE public."sponsorship_records" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated read sponsorship_records" ON public."sponsorship_records";
CREATE POLICY "Allow authenticated read sponsorship_records" ON public."sponsorship_records" FOR SELECT TO authenticated USING (true);
ALTER TABLE public."sponsorship_records" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated update sponsorship_records" ON public."sponsorship_records";
CREATE POLICY "Allow authenticated update sponsorship_records" ON public."sponsorship_records" FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
ALTER TABLE public."system_settings" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow admin full access to system settings" ON public."system_settings";
CREATE POLICY "Allow admin full access to system settings" ON public."system_settings" FOR ALL TO public USING ((((auth.jwt() ->> 'role'::text) = 'admin'::text) OR (auth.role() = 'service_role'::text)));
ALTER TABLE public."system_settings" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access to non-secret system settings" ON public."system_settings";
CREATE POLICY "Allow public read access to non-secret system settings" ON public."system_settings" FOR SELECT TO public USING (true);
ALTER TABLE public."user_roles" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admin can manage user_roles" ON public."user_roles";
CREATE POLICY "Admin can manage user_roles" ON public."user_roles" FOR ALL TO public USING ((get_user_role() = ANY (ARRAY['super_admin'::text, 'admin'::text])));
ALTER TABLE public."user_roles" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view own roles" ON public."user_roles";
CREATE POLICY "Users can view own roles" ON public."user_roles" FOR SELECT TO public USING ((auth.uid() = user_id));
ALTER TABLE public."zone_chief_assignments" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admin can manage zone_chief_assignments" ON public."zone_chief_assignments";
CREATE POLICY "Admin can manage zone_chief_assignments" ON public."zone_chief_assignments" FOR ALL TO authenticated USING ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = ANY (ARRAY['super_admin'::text, 'admin'::text])))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = ANY (ARRAY['super_admin'::text, 'admin'::text]))))));
ALTER TABLE public."zone_chief_assignments" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Anyone authenticated can read zone_chief_assignments" ON public."zone_chief_assignments";
CREATE POLICY "Anyone authenticated can read zone_chief_assignments" ON public."zone_chief_assignments" FOR SELECT TO authenticated USING (true);